### ISSUE TITLE
After uploading the AppPackage.app on App Catelog, the title, ProductID etc.. details are not recognized

### ISSUE THREAD

**Issue by azri** [OfficeDev/PHP-App-for-SharePoint#1]
We followed all the steps mentioned on the Readme. When we upload AppPackage.app in the the App Catelog, Apps for Sharepoint section, the Name, ProductID details were not recognized. So when I go to Site and try to add the app, this app is not listing.  Please check the attached screenshot.

![apps for sharepoint all apps](https://cloud.githubusercontent.com/assets/373469/7403388/256ab7a4-eea3-11e4-9ef0-855031970f8d.png)

My AppManifest.xml file content is
```
<?xml version="1.0" encoding="UTF-8" ?><App xmlns="http://schemas.microsoft.com/sharepoint/2012/app/manifest" Name="PHPAppforSharePointDemo" ProductID="{7944BC76-82CF-4807-8906-6205BB85E2FE}" SharePointMinVersion="15.0.0.0"><Properties><Title>PHP App for SharePoint</Title><StartPage>https://localhost/PHP-App-for-SharePoint/PHP/index.php?{StandardTokens}</StartPage><SupportedLocale CultureName="en-US" /></SupportedLocales></Properties><AppPrincipal><RemoteWebApplication ClientId="9df28eb2-4742-4287-8c3c-cb30a340aef1"/></AppPrincipal><AppPermissionRequests>
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="Read" />
  </AppPermissionRequests></App>
```

**Comment by Ricalo** [comment]
Azri,
Thank you for trying this sample. I was able to reproduce the issue that you describe. The issue went away when I provided my own values for:
* Name
* ProductId
* Title

In the AppManifest.xml. Here's the example that worked for me.

```xml
<?xml 
	version="1.0" encoding="UTF-8" standalone="no"?>
	<App xmlns="http://schemas.microsoft.com/sharepoint/2012/app/manifest" 
		Name="Issue1" 
		ProductID="{00BC49B1-5C39-49D7-A6A8-A556E1B70569}" SharePointMinVersion="15.0.0.0" Version="1.0.0.0">
		<Properties>
			<Title>Issue1</Title>
			<StartPage>https://localhost/phpappweb/index.php?{StandardTokens}</StartPage>
		</Properties>
		<AppPrincipal>
		<RemoteWebApplication ClientId="07d8104c-64c7-4bbf-b5ba-08a167b1e3bb"/></AppPrincipal>  <AppPermissionRequests>
    <AppPermissionRequest Scope="http://sharepoint/content/sitecollection/web" Right="Read" />
  </AppPermissionRequests></App>
```

Also, the Title in the manifest matches what I registered in the appregnew.aspx page, but I'm not sure if that's required.
Could you try providing your own values and let me know if it works for you?

**Comment by azri** [comment]
Thanks for quick response. I used Name, Title as the Appname used when I register at appregnew.aspx . Now it is working.

**Comment by Ricalo** [comment]
I tried again and Title can be something different. Name has to be the same that you specify in appregnew.aspx. I updated the readme to warn others about this. 
Thank you

**Comment by azri** [comment]
This issue came back when I use below AppManifest. 

```
<?xml 
    version="1.0" encoding="UTF-8" standalone="no"?>
    <App xmlns="http://schemas.microsoft.com/sharepoint/2012/app/manifest" 
	 Name="PHPDrupalAPP" 
        ProductID="{d486beaa-cd12-490b-9a8f-ffe68c817ef1}" SharePointMinVersion="15.0.0.0" Version="2.0.0.0">
        <Properties>
	  <Title>PHPDrupalAPP</Title>
            <StartPage>https://example.com/phpappforsharepoint?{StandardTokens}</StartPage>
        </Properties>
        <AppPrincipal>
        <RemoteWebApplication ClientId="e8408aeb-4ce0-4313-bbdf-fa0858f6b8ae"/></AppPrincipal>  
        <AppPermissionRequests>
    <AppPermissionRequest Scope="http://sharepoint/content/tenant" Right="Write" />
    <AppPermissionRequest Scope="http://sharepoint/social/tenant" Right="Write" />
  </AppPermissionRequests></App>
```

**Comment by Ricalo** [comment]
If you're registering another app, you also have to change the Name attribute.

**Comment by azri** [comment]
I used the same name used while registering app at appnewreg.aspx page. Some times it is still causing the issue. 

If the url is https://example.com/phpappforsharepoint like this, does it accept?

**Comment by Ricalo** [comment]
@azri please use a different name for the new app. That should get rid of your problem.
At this point, I'd generate a new ProductId and Name and try again.
The URL looks ok to me.

**Comment by basementjack** [comment]
I had this same problem, but am still a little unclear on what solved it, and what values need to be set to match other values in the system.

Thank you for the above replies so far!

Do you know of a good article explaining that manifest xml file, and how it's used, what each value is for etc? I feel like if I had a better understanding of the manifest, I'd be able to troubleshoot this a little easier.

Thanks.

Also, do you know of any other php examples?? the office  dev website listed only 4,  all within the last year. but back a the SP conference in 2012, they were showing this - there was a session on using PHP for office dev, way back then, so I'm thinking there is more content out there to be absorbed.

- Jack

**Comment by Ricalo** [comment]
Hey @basementjack,

[Explore the app manifest structure and the package of a SharePoint Add-in](https://msdn.microsoft.com/en-us/library/office/fp179918.aspx) has some information about the manifest hopefully it'll help you understand what is going on.

Regarding other PHP samples, please let us know in [UserVoice](https://officespdev.uservoice.com/forums/224641-general/category/72301-documentation-guidance) what kind of samples you need. That way you can help us plan new samples and documentation.

I have one question on my own. If I was going to publish some more PHP/Office samples, where would be a good place/site to announce them?

Thank you very much for your comments!

**Comment by basementjack** [comment]
I think right now the Laravel framework is pretty huge in the PHP community,  If your example used Laravel, I'd email Eric  over at Laravel-news.com he's got a newsletter that goes out to like 9500 devs.

I've some other ideas: Laravel comes with an extensible set of oauth consumers and there's a large repo of them at http://socialiteproviders.github.io/ Right now one says "Microsoft Live" I haven't tried it so I don't know if it works with o365, but in general it seems the branding has switched - I don't hear of "Live" anymore so it would be nice to see "Azure" and "Office 365" in that list.  It'd be awesome if someone from MS could have a look confirm it works with o365 and offer to help if not.

- Jack

**Comment by basementjack** [comment]
Ricalo, one more question - over on user voice,   what category do I put PHP sample requests under?

**Comment by Ricalo** [comment]
Excellent, thank you. I'll look at the Laravel community.
You can post your request under documentation/guidance.

**Comment by basementjack** [comment]
Thanks Ricalo, I've posted the request on uservoice. If you want a guided tour of the laravel ecosystem, let me know. The company I work for is federated with MS on lync so it's a cinch to do a screenshare at any time.

**Comment by Ricalo** [comment]
Nice, thank you! You can contact me at http://twitter.com/ricalo to talk more about the PHP ecosystem.

**Comment by Ricalo** [comment]
Oh, and BTW @basementjack
https://github.com/OfficeDev/O365-PHP-Unified-API-Connect

**Comment by basementjack** [comment]
Thanks for the link to the API connect!
